run:
  tests: true

output:
  print-issued-lines: false

linters:
  enable-all: true
  disable:
    - lll
    - gocyclo
    - gochecknoglobals
    - wsl
    - whitespace
    - godox
    - funlen
    - gocognit
    - gomnd
    - godot
    - nestif
    - testpackage
    - nolintlint
    - wrapcheck
    - gci
    - gofumpt
    - gocritic
    - nlreturn
    - errorlint
    - nakedret
    - forbidigo
    - revive
    - cyclop
    - paralleltest
    - wastedassign
    - forcetypeassert
    - gomoddirectives
    - varnamelen
    - exhaustruct
    - ireturn
    - nonamedreturns
    - errname
    - nilnil
    - maintidx
    - unused # Does not work with type parameters
    - dupword
    - depguard
    - mnd
    - execinquery
    - exportloopref
    - err113

linters-settings:
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 100
  goconst:
    min-len: 8
    min-occurrences: 3
  exhaustive:
    default-signifies-exhaustive: true

issues:
  max-per-linter: 0
  exclude-dirs:
    - _examples
  max-same: 0
  exclude-use-default: false
  exclude:
    # Captured by errcheck.
    - '^(G104|G204|G307):'
    # Very commonly not checked.
    - 'Error return value of .(.*\.Help|.*\.MarkFlagRequired|(os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked'
    - 'exported method `(.*\.MarshalJSON|.*\.UnmarshalJSON|.*\.EntityURN|.*\.GoString|.*\.Pos)` should have comment or be unexported'
    - 'uses unkeyed fields'
    - 'declaration of "err" shadows declaration'
    - 'bad syntax for struct tag key'
    - 'bad syntax for struct tag pair'
    - '^ST1012'
